-- SmartClinic schema for Vercel Postgres / Neon / any Postgres
-- Run this in your Postgres SQL editor (Vercel Dashboard, Neon, etc.)

-- profiles: all users (id generated by app on signup)
create table if not exists profiles (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('patient', 'admin', 'doctor')) default 'patient',
  phone text,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- services: clinic services
create table if not exists services (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  duration_minutes int not null default 30,
  price decimal(10,2),
  is_active boolean default true,
  created_at timestamptz default now()
);

-- doctors: doctor info linked to profile
create table if not exists doctors (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references profiles(id) on delete cascade unique,
  specialty text not null,
  bio text,
  is_available boolean default true,
  created_at timestamptz default now()
);

-- doctor_schedules: availability per day
create table if not exists doctor_schedules (
  id uuid primary key default gen_random_uuid(),
  doctor_id uuid not null references doctors(id) on delete cascade,
  day_of_week int not null check (day_of_week >= 0 and day_of_week <= 6),
  start_time time not null,
  end_time time not null,
  created_at timestamptz default now(),
  unique(doctor_id, day_of_week)
);

-- appointments
create table if not exists appointments (
  id uuid primary key default gen_random_uuid(),
  patient_id uuid not null references profiles(id) on delete cascade,
  doctor_id uuid not null references doctors(id) on delete cascade,
  service_id uuid not null references services(id) on delete restrict,
  appointment_date date not null,
  appointment_time time not null,
  status text not null check (status in ('booked', 'confirmed', 'checked_in', 'completed', 'cancelled')) default 'booked',
  notes text,
  created_at timestamptz default now()
);

-- queue_entries: same-day queue
create table if not exists queue_entries (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references appointments(id) on delete cascade unique,
  queue_number int not null,
  status text not null check (status in ('waiting', 'in_progress', 'completed')) default 'waiting',
  checked_in_at timestamptz,
  created_at timestamptz default now()
);

-- notifications
create table if not exists notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  title text not null,
  message text not null,
  type text default 'info',
  is_read boolean default false,
  created_at timestamptz default now()
);

-- Optional seed
-- insert into services (name, description, duration_minutes, price) values
--   ('General Checkup', 'Routine health assessment', 30, 50),
--   ('Consultation', 'One-on-one consultation', 20, 75),
--   ('Follow-up', 'Follow-up visit', 15, 40)
-- on conflict do nothing;
