-- SmartClinic: Seed many services (run once in Neon SQL Editor after postgres-schema.sql)
-- This populates the Services page and the "Choose service" step on Book an appointment.

INSERT INTO services (name, description, duration_minutes, price) VALUES
  ('General Checkup', 'Routine health assessment and preventive care.', 30, 50),
  ('Consultation', 'One-on-one time with your doctor to discuss concerns.', 20, 75),
  ('Follow-up', 'Track progress and adjust treatment as needed.', 15, 40),
  ('Vaccination', 'Immunization and routine vaccines.', 15, 35),
  ('Blood Pressure Check', 'Quick BP reading and heart rate check.', 10, 25),
  ('Diabetes Screening', 'Blood sugar check and diabetes management review.', 20, 45),
  ('Physical Examination', 'Full body physical exam for wellness or clearance.', 45, 90),
  ('Wellness Visit', 'Annual wellness and preventive health visit.', 30, 60),
  ('Minor Injury / Wound Care', 'Assessment and care for minor cuts, burns, or wounds.', 20, 55),
  ('Skin Check', 'Skin examination and mole check.', 20, 50),
  ('ENT Visit', 'Ear, nose, and throat examination.', 25, 65),
  ('Eye Examination', 'Basic vision and eye health check.', 30, 70),
  ('Mental Health Consultation', 'Discussion and support for mental wellness.', 45, 120),
  ('Pediatric Checkup', 'Well-child visit and developmental check.', 25, 55),
  ('Women''s Health', 'Gynecological exam and women''s wellness.', 30, 85),
  ('Travel Health', 'Travel vaccines and health advice for trips.', 25, 65),
  ('Lab Results Review', 'Review and explain blood work or other lab results.', 15, 40),
  ('Chronic Disease Management', 'Ongoing care for diabetes, hypertension, etc.', 30, 70),
  ('Asthma / COPD Check', 'Lung function and breathing assessment.', 20, 50),
  ('ECG / Heart Check', 'Electrocardiogram and heart health review.', 25, 80),
  ('X-Ray Review', 'Review of X-rays or other imaging with your doctor.', 15, 45),
  ('Prescription Refill', 'Medication review and refill authorization.', 10, 30),
  ('Nutrition Counseling', 'Diet and nutrition advice for health goals.', 30, 75),
  ('Smoking Cessation', 'Support and plan to quit smoking.', 25, 60),
  ('Weight Management', 'Weight and lifestyle counseling.', 30, 70),
  ('Allergy Consultation', 'Allergy assessment and treatment options.', 25, 65),
  ('Flu Shot', 'Seasonal influenza vaccination.', 10, 30),
  ('COVID-19 Vaccine', 'COVID-19 vaccination and boosters.', 15, 0),
  ('Sports Physical', 'Physical exam for sports participation clearance.', 25, 55),
  ('Pre-employment Physical', 'Health check required for new employment.', 30, 75),
  ('School Physical', 'Annual exam for school requirements.', 25, 50),
  ('DOT Physical', 'Commercial driver medical examination.', 35, 95),
  ('Minor Procedure', 'Stitches removal, wart treatment, small procedures.', 20, 60),
  ('Urgent Care Visit', 'Same-day care for non-emergency illness or injury.', 25, 85),
  ('Telehealth Consultation', 'Video or phone visit with your doctor.', 20, 55),
  ('Ear Wax Removal', 'Safe removal of impacted ear wax.', 15, 45),
  ('Pregnancy Test & Counseling', 'Testing and early pregnancy counseling.', 20, 50),
  ('STI Screening', 'Confidential screening and treatment.', 20, 60),
  ('Thyroid Check', 'Thyroid function review and management.', 20, 55),
  ('Vitamin B12 / Iron', 'Shot or counseling for deficiency.', 10, 35);
-- Run this script only once in Neon SQL Editor. If you run it again, you will get duplicate services.
